/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FeatureItem from "./FeatureItem";

const features = ["Concentrated Liquidity", "Dynamic Fees", "Farming"];

const AvantGardeSection: React.FC = () => (
    <section className="flex flex-col justify-center">
        <h1 className="text-7xl text-pink-600 font-extended max-md:max-w-full max-md:text-4xl max-md:leading-10">
            The avant-garde tech for enhanced trading & LP experience
        </h1>
        <ul className="flex flex-col gap-2 mt-16 w-full text-black max-md:mt-10 max-md:max-w-full">
            {features.map((feature, index) => (
                <FeatureItem key={index} title={feature} />
            ))}
        </ul>
    </section>
);

export default AvantGardeSection;
